kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-reader-binding
  namespace: default
subjects:
# Google Cloud user account
- kind: User
  name: joyceljy6256@gmail.com
- kind: User
  name: daumantas.patapas@gmail.com
- kind: User
  name: marcel.stelte@gmail.com
# Kubernetes service account
- kind: ServiceAccount
  name: dbaccess
# IAM service account
- kind: User
  name: 565041184582@cloudbuild.gserviceaccount.com
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io