apiVersion: apps/v1
kind: Deployment
metadata:
  name: sc-netcore3-deployment
  labels: 
    app: netcore 
spec:
  selector:
    matchLabels:
      app: sc-netcore3-pod
  template:
    metadata:
      labels:
        app: sc-netcore3-pod
    spec:
      containers:
      - name: sc-netcore3-container
        image: gcr.io/sc-g22/net:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80