apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-deployment
  labels:
    app: angular
spec:
  replicas: 1
  selector:
    matchLabels:
      app: angular
      version: v1.0.0
  template:
    metadata:
      labels:
        app: angular
        version: v1.0.0
    spec:
      containers:
      - name: angular-container
        image: gcr.io/sc-g22/angular:v1
        imagePullPolicy: "Always"
        resources:
          requests:
            memory: "128Mi"
            cpu: "1m"
        ports:
        - containerPort: 80
        env:
        - name: VERSION
          value: v1.0.0
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "angular-hpa-crkb"
  namespace: "default"
  labels:
    app: "angular"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "angular"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80
