apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "angular-hpa-crkb"
  namespace: "default"
  labels:
    app: "angular"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "angular-deployment"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 1
