apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.metadata.name }}
  labels:
    {{- include "sc22-g22-db-chart.labels" . | nindent 4 }}
data:
  POSTGRES_DB: {{ .Values.configMap.data.POSTGRES_DB }}
  POSTGRES_USER: {{ .Values.configMap.data.POSTGRES_USER }}