apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.metadata.name }}
data:
  POSTGRES_DB: {{ .Values.configMap.data.POSTGRES_DB }}
  POSTGRES_USER: {{ .Values.configMap.data.POSTGRES_USER }}