apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.metadata.name }}
  labels:
    {{- include "sc22-g22-db-chart.labels" . | nindent 4 }}
type: Opaque
data:
  POSTGRES_PASSWORD: YWRtaW4xMjMK